accountConfig:
  idUri: "sip:6001@192.168.1.249"
  AccountRegConfig:
    registrarUri: "sip:192.168.1.249"
    registerOnAdd: true
  AccountSipConfig:
    authCreds:
      - { scheme: "digest", realm: "*", username: "6001", dataType: 0, data: "s3cret" }
audDevOrder:
  - "JBR APP"
  - "MacBook Pro"
